/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecole;

import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.admin;
import utils.DB;
import utils.fonction;
import javax.swing.ImageIcon;


/**
 *
 * @author Alfousseni
 */
public class inscriptionAdmin extends javax.swing.JFrame {
    private static DB db;
    private  fonction f;
    /**
     * Creates new form inscriptionAdmin
     */
    public inscriptionAdmin() {
         try{
        initComponents();
        setLocationRelativeTo(null);
        db = DB.getInstance();
        
        
        }catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        prenom_txt = new javax.swing.JTextField();
        nom_txt = new javax.swing.JTextField();
        adminEnregistrement_btn = new javax.swing.JButton();
        password_tx = new javax.swing.JPasswordField();
        confirme_txt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ENREGISTREMENT");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOM");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PRENOM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("LOGIN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PASSWORD");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CONFIRME PASSWORD");

        login_txt.setBackground(new java.awt.Color(255, 255, 255));

        email_txt.setBackground(new java.awt.Color(255, 255, 255));

        prenom_txt.setBackground(new java.awt.Color(255, 255, 255));

        nom_txt.setBackground(new java.awt.Color(255, 255, 255));

        adminEnregistrement_btn.setBackground(new java.awt.Color(0, 0, 255));
        adminEnregistrement_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminEnregistrement_btn.setText("Enregistrement");
        adminEnregistrement_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEnregistrement_btnActionPerformed(evt);
            }
        });

        password_tx.setBackground(new java.awt.Color(255, 255, 255));
        password_tx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_tx.setForeground(new java.awt.Color(0, 0, 0));
        password_tx.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        confirme_txt.setBackground(new java.awt.Color(255, 255, 255));
        confirme_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirme_txt.setForeground(new java.awt.Color(0, 0, 0));
        confirme_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(36, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_txt)
                    .addComponent(email_txt)
                    .addComponent(prenom_txt)
                    .addComponent(nom_txt)
                    .addComponent(password_tx, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(confirme_txt))
                .addGap(162, 162, 162))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(adminEnregistrement_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prenom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(email_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(login_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(password_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirme_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(adminEnregistrement_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminEnregistrement_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEnregistrement_btnActionPerformed
        // TODO add your handling code here:
        try{
             if (!f.testField(nom_txt.getText(), prenom_txt.getText(), password_tx.getText(), login_txt.getText(), email_txt.getText())) {
                 JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs");
                 return;
             } 
             String nom=nom_txt.getText();
             String prenom=prenom_txt.getText();
             String password = new String(password_tx.getPassword());
             String login=login_txt.getText();
             String email=email_txt.getText();
             String confirmPassword = new String(confirme_txt.getPassword());
             
             if(f.contole(nom,prenom)){
                  JOptionPane.showMessageDialog(this, "Verifier la taille du nom et prenom","email",JOptionPane.ERROR_MESSAGE);
                  return;
             }
             if(!f.confirmPassword(password, confirmPassword)){
                  JOptionPane.showMessageDialog(this, "Les mots de passe ne son pas similaire","password",JOptionPane.ERROR_MESSAGE);
                  return;
             }
             if(verificationLogin(login,email) == 1){
                   JOptionPane.showMessageDialog(this, "ce login existe deja","login",JOptionPane.ERROR_MESSAGE);
                   return;
             }
             if(verificationLogin(login,email) == 2){
                   JOptionPane.showMessageDialog(this, "cet email existe deja","email",JOptionPane.ERROR_MESSAGE);
                  
                   return;
             }
             if(!f.validerEmail(email)){
                JOptionPane.showMessageDialog(this, "email non confome(min3char@min3char.min2char)","email",JOptionPane.ERROR_MESSAGE);
                return;
             }
             
             admin ad= new admin(nom, prenom, login, email, password);
             int row=insertion(ad);
             if(row==1){
             JOptionPane.showMessageDialog(this, "Valider, vous pouvez maintenant vous connecter", "Validation réussie", JOptionPane.INFORMATION_MESSAGE);
             login Login=new login();
             Login.setVisible(true);
             this.setVisible(false);
             }
             
         } catch (Exception ex) {
            Logger.getLogger(inscriptionAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminEnregistrement_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login Login=new login();
             Login.setVisible(true);
             this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(inscriptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(inscriptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(inscriptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(inscriptionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new inscriptionAdmin().setVisible(true);
//            }
//        });
//    }
    
    private static int insertion(admin admin){
         try {
            int a = 0;
            String insertion = "insert into admin(nom_admin,prenom,login,password,email) values(?,?,?,?,?)";

            db.iniPreparedCmd(insertion);
            db.getPstmt().setString(4, admin.getPassword());
            db.getPstmt().setString(2, admin.getPrenom());
            db.getPstmt().setString(1, admin.getNom());
            db.getPstmt().setString(3, admin.getLogin());
            db.getPstmt().setString(5, admin.getEmail());

            a = db.executePreparedCUD();

            if (a != 0) {
                return 1;
            }

        } catch (Exception ex) {
            Logger.getLogger(inscriptionAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    
    private static int verificationLogin(String login,String email){
    try{
        String recuplogin=String.format("select id from admin where login='%s'", login);
        String recupemail=String.format("select id from admin where email='%s'", email);
        db.iniPreparedCmd(recuplogin);
        ResultSet log= db.executeSelect(recuplogin);
        if(log.next()){
            return 1;
        }
        db.iniPreparedCmd(recupemail);
        ResultSet mail= db.executeSelect(recupemail);
        if(mail.next()){
            return 2;
        }

        } catch (Exception ex) {
           Logger.getLogger(inscriptionAdmin.class.getName()).log(Level.SEVERE, null, ex);
       }
    return -1;
    }
    
    private void clearFied() {
        prenom_txt.setText("");
        nom_txt.setText("");
        email_txt.setText("");
        login_txt.setText("");
        password_tx.setText("");
        confirme_txt.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminEnregistrement_btn;
    private javax.swing.JPasswordField confirme_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login_txt;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JPasswordField password_tx;
    private javax.swing.JTextField prenom_txt;
    // End of variables declaration//GEN-END:variables
}
